export enum ORDER_STATUS{
    NEW="NEW", CLOSED="CLOSED", SENT="SENT", ACCEPTED="ACCEPTED"
}

export enum PayType{
    CASH='CASH', PAYME='PAYME', CLICK='CLICK'
}

export enum HumanStatus {
    BLOCKED='BLOCKED', ACTIVE='ACTIVE', DELETED='DELETED'
}

export enum Region{
    TASHKENT='TASHKENT', TASHKENT_REGION='TASHKENT_REGION', SAMARKAND='SAMARKAND', BUKHARA='BUKHARA'
}

export enum Language {
    RUSSIA='RUSSIAN', UZBEK='UZBEK'
}

export enum HumanType {
    ADMIN= 'ADMIN', CLIENT='CLIENT', OPERATOR='OPERATOR', COURIER='COURIER'
}